spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CareerPathway_test
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop